/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import javax.swing.UIManager;



/**
 *
 * @author LENOVO
 */
public class bukutamu extends javax.swing.JFrame {

    /**
     * Creates new form bukutamu
     */
    public bukutamu() {
        initComponents();
        clear();
    }
    
    public void clear()
    {
        txtnim.setText("");
        lblnotif.setText("...");
        txtnama.setText("");
        txtjurusan.setText("");
        txtjurusan.setText("");
        btnBacaBuku.setVisible(false);
        btnPinjamBuku.setVisible(false);
        btnCarireferensi.setVisible(false);
        btnDuduk.setVisible(false);
    }
    
    
    public void nimNotFound()
    {
        lblnotif.setText("Nim tidak ditemukan!");
        txtnama.setText("...");
        txtjurusan.setText("...");
        txtjk.setText("...");
        lblnotif.setForeground(Color.red);
        btnBacaBuku.setVisible(false);
        btnPinjamBuku.setVisible(false);
        btnCarireferensi.setVisible(false);
        btnDuduk.setVisible(false);
        
    }
    
    
    public void submit(String tujuan)
    {
        
        try
        {
             SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");  
             Date date = new Date();  

             java.sql.Connection conn=(Connection)koneksi.configDB();
             String sql="insert into bukutamu(nim,tanggal,keperluan) values(?,?,?)";
             PreparedStatement pst=conn.prepareStatement(sql);
             pst.setString(1, txtnim.getText().trim());
             pst.setString(2,formatter.format(date) );
             pst.setString(3, tujuan);
             pst.executeUpdate();

             JOptionPane.showMessageDialog(null, "Berhasil menambah data pengunjung, Terima Kasih!");

             clear();
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog( null, e.getMessage());
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtnim = new javax.swing.JTextField();
        txtnama = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtjurusan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtjk = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnDuduk = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblnotif = new javax.swing.JLabel();
        btnPinjamBuku = new javax.swing.JButton();
        btnBacaBuku = new javax.swing.JButton();
        btnCarireferensi = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnim.setForeground(new java.awt.Color(33, 152, 207));
        txtnim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 152, 207)));
        txtnim.setCaretColor(new java.awt.Color(33, 152, 207));
        txtnim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnimKeyReleased(evt);
            }
        });
        jPanel1.add(txtnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 170, 30));

        txtnama.setForeground(new java.awt.Color(33, 152, 207));
        txtnama.setText("...");
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 125, -1, -1));

        jLabel3.setForeground(new java.awt.Color(33, 152, 207));
        jLabel3.setText("Nama:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 125, -1, -1));

        jLabel4.setForeground(new java.awt.Color(33, 152, 207));
        jLabel4.setText("Cari Nim Anda:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel5.setForeground(new java.awt.Color(33, 152, 207));
        jLabel5.setText("Jurusan:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 164, -1, -1));

        txtjurusan.setForeground(new java.awt.Color(33, 152, 207));
        txtjurusan.setText("...");
        jPanel1.add(txtjurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 164, -1, -1));

        jLabel7.setForeground(new java.awt.Color(33, 152, 207));
        jLabel7.setText("Jenis Kelamin:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 203, -1, -1));

        txtjk.setForeground(new java.awt.Color(33, 152, 207));
        txtjk.setText("...");
        jPanel1.add(txtjk, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 203, -1, -1));

        jLabel9.setForeground(new java.awt.Color(33, 152, 207));
        jLabel9.setText("Keperluan:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 242, -1, -1));

        btnDuduk.setBackground(new java.awt.Color(33, 152, 207));
        btnDuduk.setForeground(new java.awt.Color(255, 255, 255));
        btnDuduk.setText("Duduk aja");
        btnDuduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDudukActionPerformed(evt);
            }
        });
        jPanel1.add(btnDuduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 328, 93, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Login?, Klik disini");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        lblnotif.setForeground(new java.awt.Color(33, 152, 207));
        lblnotif.setText("...");
        jPanel1.add(lblnotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        btnPinjamBuku.setBackground(new java.awt.Color(33, 152, 207));
        btnPinjamBuku.setForeground(new java.awt.Color(255, 255, 255));
        btnPinjamBuku.setText("Pinjam Buku");
        btnPinjamBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinjamBukuActionPerformed(evt);
            }
        });
        jPanel1.add(btnPinjamBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 274, 99, -1));

        btnBacaBuku.setBackground(new java.awt.Color(33, 152, 207));
        btnBacaBuku.setForeground(new java.awt.Color(255, 255, 255));
        btnBacaBuku.setText("Baca Buku");
        btnBacaBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacaBukuActionPerformed(evt);
            }
        });
        jPanel1.add(btnBacaBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 274, 93, -1));

        btnCarireferensi.setBackground(new java.awt.Color(33, 152, 207));
        btnCarireferensi.setForeground(new java.awt.Color(255, 255, 255));
        btnCarireferensi.setText("cari Referensi");
        btnCarireferensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarireferensiActionPerformed(evt);
            }
        });
        jPanel1.add(btnCarireferensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 328, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 135, 440, 440));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 690, 390));

        jPanel2.setBackground(new java.awt.Color(33, 152, 207));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 29)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buku Tamu Perpustakaan STTINDONESIA");

        jLabel6.setBackground(new java.awt.Color(33, 152, 207));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("x");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(33, 152, 207));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("-");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(640, 640, 640)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jLabel1))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 210));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void btnDudukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDudukActionPerformed
        // TODO add your handling code here:
      
        submit("duduk aja");
        
    }//GEN-LAST:event_btnDudukActionPerformed

    private void txtnimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnimKeyReleased
        // TODO add your handling code here:
        try 
        {
           java.sql.Connection conn=(Connection)koneksi.configDB();
           String sql="select nama, jurusan, jk from mahasiswa where nim=?";
           PreparedStatement pst=conn.prepareStatement(sql);
           pst.setString(1, txtnim.getText().trim());
           ResultSet rs=pst.executeQuery();

           if(rs.next())
           {
               txtnama.setText(rs.getString("nama"));
               txtjk.setText(rs.getString("jk"));
               txtjurusan.setText(rs.getString("jurusan"));
               lblnotif.setForeground(Color.GREEN);
               btnBacaBuku.setVisible(true);
               btnPinjamBuku.setVisible(true);
               btnCarireferensi.setVisible(true);
               btnDuduk.setVisible(true);
               lblnotif.setText("Nim Ditemukan");
           }
           
           else if(txtnim.getText().trim().equals(""))
           {
               lblnotif.setText("...");
               txtnama.setText("...");
               txtjurusan.setText("...");
               txtjk.setText("...");
               btnBacaBuku.setVisible(false);
               btnPinjamBuku.setVisible(false);
               btnCarireferensi.setVisible(false);
               btnDuduk.setVisible(false);
             
           }
           
           else
           {
              nimNotFound();
           }
           
        }
        
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
      
    }//GEN-LAST:event_txtnimKeyReleased

    private void btnPinjamBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinjamBukuActionPerformed
        // TODO add your handling code here:
        submit("pinjam buku");
    }//GEN-LAST:event_btnPinjamBukuActionPerformed

    private void btnBacaBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacaBukuActionPerformed
        // TODO add your handling code here:
        submit("baca buku");
    }//GEN-LAST:event_btnBacaBukuActionPerformed

    private void btnCarireferensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarireferensiActionPerformed
        // TODO add your handling code here:
        submit("cari referensi");
    }//GEN-LAST:event_btnCarireferensiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bukutamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bukutamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bukutamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bukutamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bukutamu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBacaBuku;
    private javax.swing.JButton btnCarireferensi;
    private javax.swing.JButton btnDuduk;
    private javax.swing.JButton btnPinjamBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblnotif;
    private javax.swing.JLabel txtjk;
    private javax.swing.JLabel txtjurusan;
    private javax.swing.JLabel txtnama;
    private javax.swing.JTextField txtnim;
    // End of variables declaration//GEN-END:variables
}
