/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import koneksi.koneksi;

/**
 *
 * @author LENOVO
 */
public class databukutamu extends javax.swing.JFrame {

    /**
     * Creates new form databukutamu
     */
    DefaultTableModel model=new DefaultTableModel();
    
    public databukutamu() {
        initComponents();
        tableheader();
        filltable();
    }
    
    public void hitungkunjungan(String nim)
    {
        try
        {
          java.sql.Connection conn=(Connection)koneksi.configDB();
          String sql="select count(nim) as kunjungan from bukutamu where nim=?";
          PreparedStatement pst=conn.prepareStatement(sql);
          pst.setString(1, nim);
          ResultSet rs=pst.executeQuery();
          
          if(rs.next())
          {
            lblkunjungan.setText(rs.getString("kunjungan"));
          }
          
        }
        
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        
       
        
    }
    
    public void tableheader()
    {
        model.addColumn("Nim");
        model.addColumn("Nama");
        model.addColumn("No.Telp");
        model.addColumn("Jurusan");
        model.addColumn("Alamat");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Keperluan");
        model.addColumn("Tanggal");
        
        tblmhs.setModel(model);
    }
    
    public void filltable()
    {
        
        try 
        {
           model = (DefaultTableModel)tblmhs.getModel();
           model.getDataVector().removeAllElements();
           model.fireTableDataChanged(); 
            
           java.sql.Connection conn=(Connection) koneksi.configDB();
           String sql="select mahasiswa.*,bukutamu.* from mahasiswa inner join bukutamu on mahasiswa.nim=bukutamu.nim";
           PreparedStatement pst=conn.prepareStatement(sql);
           ResultSet rs=pst.executeQuery();
           
           while(rs.next())
           {
               model.addRow(new Object[]{
                 rs.getString("nim"),
                 rs.getString("nama"),
                 rs.getString("notelp"),
                 rs.getString("jurusan"),
                 rs.getString("alamat"),
                 rs.getString("jk"),
                 rs.getString("keperluan"),
                 rs.getString("tanggal")
                 
               });
           }
                   
        } 
        
        catch (Exception e) 
        {
            System.out.println(e.getMessage());
        }
        
        
        tblmhs.setModel(model);
    }
    
    
    public void filltablecount()
    {
        try 
        {
            model = (DefaultTableModel)tblmhs.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged(); 
            
            java.sql.Connection conn=(Connection)koneksi.configDB();
            String sql="";
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            
            while(rs.next())
            {
                model.addRow(new Object[]{
                
                    
                });
            }
        } 
        
        catch (Exception e) 
        {
            System.out.println(e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblnim = new javax.swing.JLabel();
        lblnama = new javax.swing.JLabel();
        lblnotelp = new javax.swing.JLabel();
        lbljurusan = new javax.swing.JLabel();
        lblalamat = new javax.swing.JLabel();
        lbljk = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbltujuan = new javax.swing.JLabel();
        lbltgl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblkunjungan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmhs = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbsearch = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(33, 152, 207));

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        rSPanelImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSPanelImage1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(rSPanelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 152, 207));
        jLabel1.setText("Data Mahasiswa");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 152, 207)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 152, 207));
        jLabel2.setText("Nim:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 32, -1, -1));

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(33, 152, 207));
        jLabel3.setText("Nama:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 67, -1, -1));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(33, 152, 207));
        jLabel4.setText("No.Telepon:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(33, 152, 207));
        jLabel5.setText("Jurusan:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 135, -1, -1));

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(33, 152, 207));
        jLabel6.setText("Alamat:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(33, 152, 207));
        jLabel7.setText("Jenis kelamin:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        lblnim.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        lblnim.setForeground(new java.awt.Color(33, 152, 207));
        lblnim.setText("...");
        jPanel3.add(lblnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 38, -1, -1));

        lblnama.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        lblnama.setForeground(new java.awt.Color(33, 152, 207));
        lblnama.setText("...");
        jPanel3.add(lblnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 68, -1, -1));

        lblnotelp.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        lblnotelp.setForeground(new java.awt.Color(33, 152, 207));
        lblnotelp.setText("...");
        jPanel3.add(lblnotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        lbljurusan.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        lbljurusan.setForeground(new java.awt.Color(33, 152, 207));
        lbljurusan.setText("...");
        jPanel3.add(lbljurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 135, -1, -1));

        lblalamat.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        lblalamat.setForeground(new java.awt.Color(33, 152, 207));
        lblalamat.setText("...");
        jPanel3.add(lblalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        lbljk.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        lbljk.setForeground(new java.awt.Color(33, 152, 207));
        lbljk.setText("...");
        jPanel3.add(lbljk, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(33, 152, 207));
        jLabel8.setText("Tujuan:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(33, 152, 207));
        jLabel9.setText("Tanggal:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        lbltujuan.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        lbltujuan.setForeground(new java.awt.Color(33, 152, 207));
        lbltujuan.setText("...");
        jPanel3.add(lbltujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        lbltgl.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        lbltgl.setForeground(new java.awt.Color(33, 152, 207));
        lbltgl.setText("...");
        jPanel3.add(lbltgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(33, 152, 207));
        jLabel11.setText("Jml.Kunjungan:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        lblkunjungan.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        lblkunjungan.setForeground(new java.awt.Color(33, 152, 207));
        lblkunjungan.setText("...");
        jPanel3.add(lblkunjungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        tblmhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblmhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmhs);

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        jLabel10.setText("Cari:");

        cbsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nim", "Nama" }));

        jLabel12.setBackground(new java.awt.Color(33, 152, 207));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(33, 152, 207));
        jLabel12.setText("-");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(33, 152, 207));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(33, 152, 207));
        jLabel13.setText("x");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbsearch, 0, 156, Short.MAX_VALUE)
                                            .addComponent(txtcari))))
                                .addGap(15, 15, 15))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        // TODO add your handling code here:
        try 
        {
            
            model = (DefaultTableModel)tblmhs.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged(); 
           
            java.sql.Connection conn=(Connection)koneksi.configDB();
            String sql="select mahasiswa.*,bukutamu.* from mahasiswa inner join bukutamu on mahasiswa.nim=bukutamu.nim where mahasiswa."+cbsearch.getSelectedItem()+" like ?";
            PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1,"%"+txtcari.getText()+"%");
            ResultSet rs=pst.executeQuery();
            
            while(rs.next())
            {
                model.addRow(new Object[]{
                    
                    rs.getString("mahasiswa.nim"),
                    rs.getString("nama"),
                    rs.getString("notelp"),
                    rs.getString("jurusan"),
                    rs.getString("alamat"),
                    rs.getString("jk"),
                    rs.getString("keperluan"),
                    rs.getString("tanggal")
                    
                });
                
            }
            
            tblmhs.setModel(model);
        } 
        
        catch (Exception e) 
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_txtcariKeyReleased

    private void tblmhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmhsMouseClicked
        // TODO add your handling code here:
        int baris = tblmhs.getSelectedRow();
        String nim=tblmhs.getValueAt(baris, 0).toString();
        lblnim.setText(tblmhs.getValueAt(baris, 0).toString());
        lblnama.setText(tblmhs.getValueAt(baris, 1).toString());
        lblnotelp.setText(tblmhs.getValueAt(baris, 2).toString());
        lbljurusan.setText(tblmhs.getValueAt(baris, 3).toString());
        lblalamat.setText(tblmhs.getValueAt(baris, 4).toString());
        lbljk.setText(tblmhs.getValueAt(baris, 5).toString());
        lbltujuan.setText(tblmhs.getValueAt(baris, 6).toString());
        lbltgl.setText(tblmhs.getValueAt(baris, 7).toString());
        hitungkunjungan(nim);
    }//GEN-LAST:event_tblmhsMouseClicked

    private void rSPanelImage1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSPanelImage1MouseClicked
        // TODO add your handling code here:
        dispose();
        new grafikbukutamu().setVisible(true);

    }//GEN-LAST:event_rSPanelImage1MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        dispose();
        new bukutamu().setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(databukutamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(databukutamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(databukutamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(databukutamu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new databukutamu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblalamat;
    private javax.swing.JLabel lbljk;
    private javax.swing.JLabel lbljurusan;
    private javax.swing.JLabel lblkunjungan;
    private javax.swing.JLabel lblnama;
    private javax.swing.JLabel lblnim;
    private javax.swing.JLabel lblnotelp;
    private javax.swing.JLabel lbltgl;
    private javax.swing.JLabel lbltujuan;
    private rojerusan.RSPanelImage rSPanelImage1;
    private javax.swing.JTable tblmhs;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
