/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author LENOVO
 */
public class test extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public test() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

//    public void pie()
//    {
//        DefaultPieDataset dataset = new DefaultPieDataset();
//        dataset.setValue("TV", new Double(20));
//        dataset.setValue("DVD", new Double(20));
//        dataset.setValue("Mobile phone", new Double(40));
//        dataset.setValue("Accessories", new Double(10));
//        // create pir chart
//        JFreeChart chart = ChartFactory.createPieChart3D(
//                "Product Sales", // chart title                   
//                dataset, // data 
//                true, // include legend                   
//                true,
//                false);
//        // set chart properties
//        final PiePlot3D plot = (PiePlot3D) chart.getPlot();
//        plot.setStartAngle(270);
//        plot.setForegroundAlpha(0.60f);
//        plot.setInteriorGap(0.02);
//        // create chart panel the add it to swing panel in  jframe
//        ChartPanel chartPanel = new ChartPanel(chart);
//        pnChart.removeAll();        // clear panel before add new chart
//        pnChart.add(chartPanel, BorderLayout.CENTER);
//        pnChart.validate();         // refresh panel to display new chart
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        pif4 = new javax.swing.JLabel();
        pif1 = new javax.swing.JLabel();
        pif3 = new javax.swing.JLabel();
        pif2 = new javax.swing.JLabel();
        psi1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();
        psi2 = new javax.swing.JLabel();
        psi3 = new javax.swing.JLabel();
        psi4 = new javax.swing.JLabel();
        pka1 = new javax.swing.JLabel();
        pka2 = new javax.swing.JLabel();
        pka3 = new javax.swing.JLabel();
        pka4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtbulan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Periode I");

        p1.setText("Periode II");

        jLabel3.setText("Hasil");

        p2.setText("Periode III");

        p3.setText("Periode IV");

        pif4.setText("...");

        pif1.setText("...");

        pif3.setText("...");

        pif2.setText("...");

        psi1.setText("...");

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Jurusan:");

        p5.setText("IF");

        p6.setText("SI");

        p7.setText("KA");

        psi2.setText("...");

        psi3.setText("...");

        psi4.setText("...");

        pka1.setText("...");

        pka2.setText("...");

        pka3.setText("...");

        pka4.setText("...");

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("jButton4");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p6)
                                    .addComponent(p5)
                                    .addComponent(p7))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(psi1)
                                            .addComponent(pif1)
                                            .addComponent(pka1))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(psi2)
                                            .addComponent(pif2)
                                            .addComponent(pka2))
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(pif3)
                                            .addComponent(psi3)
                                            .addComponent(pka3))
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(pif4)
                                            .addComponent(psi4)
                                            .addComponent(pka4)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(p1)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(p2)
                                                .addGap(18, 18, 18)
                                                .addComponent(p3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton4)
                                                .addGap(30, 30, 30)
                                                .addComponent(jButton6))
                                            .addComponent(txtbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton5)
                                    .addComponent(jButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtbulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(p1)
                    .addComponent(p2)
                    .addComponent(p3))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p5)
                    .addComponent(pif1)
                    .addComponent(pif2)
                    .addComponent(pif3)
                    .addComponent(pif4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p6)
                    .addComponent(psi1)
                    .addComponent(psi2)
                    .addComponent(psi3)
                    .addComponent(psi4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p7)
                    .addComponent(pka1)
                    .addComponent(pka2)
                    .addComponent(pka3)
                    .addComponent(pka4))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
           java.sql.Connection conn=(Connection)koneksi.configDB();
           String sql="SELECT COUNT(mahasiswa.nim),mahasiswa.`jurusan`,MONTH(bukutamu.`tanggal`) AS tglhadir FROM bukutamu "
           + "INNER JOIN  mahasiswa ON bukutamu.`nim`=mahasiswa.`nim` \n" +
           "GROUP BY mahasiswa.`jurusan`,MONTH(bukutamu.`tanggal`) ORDER BY MONTH(tanggal)";
           
            PreparedStatement pst=conn.prepareStatement(sql);
            
            ResultSet rs=pst.executeQuery();
            
             while(rs.next())
              {
                if(rs.getString(3).equals("5")&& rs.getString(3)!=null)
                {
                    JOptionPane.showMessageDialog(null, rs.getString(2)+" berjumlah "+rs.getString(1)+" orang pada bulan "+rs.getString(3)  );
                    
                }
                
                else if(rs.getString(3).equals("6")&& rs.getString(3)!=null)
                {
                    JOptionPane.showMessageDialog(null, rs.getString(2)+" berjumlah "+rs.getString(1)+" orang pada bulan "+rs.getString(3));
                }
                
                else if(rs.getString(3).equals("7")&& rs.getString(3)!=null)
                {
                     JOptionPane.showMessageDialog(null, rs.getString(2)+" berjumlah "+rs.getString(1)+" orang pada bulan "+rs.getString(3));
                    
                }
                
                else if(rs.getString(3).equals("8")&& rs.getString(3)!=null)
                {
                     JOptionPane.showMessageDialog(null, rs.getString(2)+" berjumlah "+rs.getString(1)+" orang pada bulan "+rs.getString(3));
                }
                  
              }
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            Date date = new Date();
            LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            int bulan = localDate.getMonthValue();
            
            ArrayList<String> arrbulan=new ArrayList<>();
            
            switch(bulan)
            {
                case 1:
                case 2:
                case 3:
                case 4:
                    arrbulan.add("Januari");
                    arrbulan.add("Februari");
                    arrbulan.add("Maret");
                    arrbulan.add("April");
                    
                    break;
                
                case 5:
                case 6:
                case 7:
                case 8:
                    arrbulan.add("May");
                    arrbulan.add("Juni");
                    arrbulan.add("Juli");
                    arrbulan.add("Agustus");
                    break;
                    
                case 9:
                case 10:
                case 11:
                case 12:
                    arrbulan.add("September");
                    arrbulan.add("Oktober");
                    arrbulan.add("November");
                    arrbulan.add("Desember");
                break;
                   
            }
              
              
              java.sql.Connection conn=(Connection)koneksi.configDB();
              String sql="SELECT COUNT(mahasiswa.nim),mahasiswa.`jurusan`,MONTH(bukutamu.`tanggal`) AS bulan FROM bukutamu \n" +
              "INNER JOIN  mahasiswa ON bukutamu.`nim`=mahasiswa.`nim` \n" +
              "WHERE MONTH(bukutamu.`tanggal`) BETWEEN 5 AND 8 \n" +
              "GROUP BY mahasiswa.`jurusan`,MONTH(bukutamu.`tanggal`) \n" +
              "ORDER BY MONTH(tanggal) ASC ";
              PreparedStatement pst=conn.prepareStatement(sql);
              ResultSet rs=pst.executeQuery();
              
               String [][][] data = {
             {
               {"if","si","ka"},
               {"per1","per2","per3","per4"},
               {"","","",""},
               {"","","",""},
               {"","","",""}
             }
         };
         
         
          
              while(rs.next())
              {
                if(rs.getString(3).equals("5"))
                {
                    JOptionPane.showMessageDialog(null, rs.getString(2)+" berjumlah "+rs.getString(1)+" orang pada bulan "+rs.getString(3)  );
                    
                }
                
                else if(rs.getString(3).equals("6"))
                {
                    JOptionPane.showMessageDialog(null, rs.getString(2)+" berjumlah "+rs.getString(1)+" orang pada bulan "+rs.getString(3));
                }
                
                else if(rs.getString(3).equals("7"))
                {
                     //JOptionPane.showMessageDialog(null, rs.getString(2)+" berjumlah "+rs.getString(1)+" orang pada bulan "+rs.getString(3));
                    
                }
                
                else if(rs.getString(3).equals("8"))
                {
                     JOptionPane.showMessageDialog(null, rs.getString(2)+" berjumlah "+rs.getString(1)+" orang pada bulan "+rs.getString(3));
                }
                  
              }
              
              
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         String [][][] data = {
             {
               {"if","si","ka"},
               {"per1","per2","per3","per4"},
               {"20","4","5","2"},
               {"2","15","7","5"},
               {"5","6","7","8"}
             }
         };
         
         
         pif1.setText(data[0][2][0]);
         pif2.setText(data[0][2][1]);
         pif3.setText(data[0][2][2]);
         pif4.setText(data[0][2][3]);
//         
         psi1.setText(data[0][3][0]);
         psi2.setText(data[0][3][1]);
         psi3.setText(data[0][3][2]);
         psi4.setText(data[0][3][3]);
         
         pka1.setText(data[0][4][0]);
         pka2.setText(data[0][4][1]);
         pka3.setText(data[0][4][2]);
         pka4.setText(data[0][4][3]);
         
         
//         for(int i=0;i<=3;i++)
//         {
//             data[0][2][i];
//         }
         
//         JOptionPane.showMessageDialog(null, data[0][0][1]);
         
     
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try 
        {
            java.sql.Connection conn=(Connection)koneksi.configDB();
              String sql="SELECT COUNT(mahasiswa.nim),mahasiswa.`jurusan`,MONTH(bukutamu.`tanggal`) AS bulan FROM bukutamu \n" +
              "INNER JOIN  mahasiswa ON bukutamu.`nim`=mahasiswa.`nim` \n" +
              "WHERE MONTH(bukutamu.`tanggal`) BETWEEN 5 AND 8 \n" +
              "GROUP BY mahasiswa.`jurusan`,MONTH(bukutamu.`tanggal`) \n" +
              "ORDER BY MONTH(tanggal),mahasiswa.`jurusan` ";
              PreparedStatement pst=conn.prepareStatement(sql);
              ResultSet rs=pst.executeQuery();
              
            ArrayList<String>periode1=new ArrayList<>();
            ArrayList<String>periode2=new ArrayList<>();
            ArrayList<String>periode3=new ArrayList<>();
            ArrayList<String>periode4=new ArrayList<>();
              
              while(rs.next())
              {
                   if(rs.getString(3).equals("5"))
                   {
                       
                   }
                   
                   else if(rs.getString(3).equals("6"))
                   {
                       
                   }
                   
                   else if(rs.getString(3).equals("7"))
                   {
                       periode3.add(rs.getString(1));
                   }
                   
                   else if(rs.getString(3).equals("8"))
                   {
                       periode4.add(rs.getString(1));
                   }
                   
                   
                   
              }
              
              
              for (int i=0;i<periode3.size();i++)
              {
                 if(periode3.size()<3)
                  {
                      periode3.add("0");
                  }
                  JOptionPane.showMessageDialog(null,"Periode 3:"+ periode3.get(i));
              }
              
              for (int i=0;i<periode4.size();i++)
              {
                  if(periode4.size()<3)
                  {
                      periode4.add("0");
                  }
                   JOptionPane.showMessageDialog(null,"Periode 4:"+ periode4.get(i));
              }
        } 
        
        catch (Exception e) 
        {
           System.out.println(e.getMessage());
        }
        
            

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ArrayList<String>per1=new ArrayList();
        ArrayList<String>per2=new ArrayList();
        ArrayList<String>per3=new ArrayList();
        ArrayList<String>per4=new ArrayList();
       
        
        
//        for (int i=0;i<arr.size();i++)
//        {
//            if(arr.size()<4)
//            {
//                arr.add("0");
//            }
//            
//            JOptionPane.showMessageDialog(null, arr.get(i));
//        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try
        {
             String monthName =txtbulan.getText(); 
            Date date = new SimpleDateFormat("MMMM",Locale.getDefault()).parse(monthName);
            Calendar cal = Calendar.getInstance();
            cal.setTime(date);
    //        println(cal.get(Calendar.MONTH));
            JOptionPane.showMessageDialog(null, cal.get(Calendar.MONTH)+1);
        }
       
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p7;
    private javax.swing.JLabel pif1;
    private javax.swing.JLabel pif2;
    private javax.swing.JLabel pif3;
    private javax.swing.JLabel pif4;
    private javax.swing.JLabel pka1;
    private javax.swing.JLabel pka2;
    private javax.swing.JLabel pka3;
    private javax.swing.JLabel pka4;
    private javax.swing.JLabel psi1;
    private javax.swing.JLabel psi2;
    private javax.swing.JLabel psi3;
    private javax.swing.JLabel psi4;
    private javax.swing.JTextField txtbulan;
    // End of variables declaration//GEN-END:variables
}
